/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.github.woodpeckeryt.youtracksdk;

import io.github.woodpeckeryt.youtracksdk.transport.YouTrackTransport;

import java.io.IOException;

public class Library {
    public static void main(String[] args) throws IOException {
        YouTrackTransport transport = new YouTrackTransport();
        transport.sendGetRequest();
    }
}
